atualizando componentes de input
devs-jequie/site-frontend pull request #15
Opened 2022-10-16 22:11 UTC by bruno34154

2022-10-16 23:10 UTC, tuliocll requested changes
@bruno34154 da uma olhada nas considerações que fiz.

2022-10-16 23:10 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
> +    setValue(e.target.value.slice(12));
Aqui, onde você pega o nome do arquivo pelo `target`, você pode pegar direto pela propriedade `files`, fica mais limpo o código e mais seguro a execução.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#getting_information_on_selected_files

2022-10-16 23:10 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
>    const handleSubmit = async (e) => {
Faz a tipagem do `e` (legal renomear ele para `event` também, para ficar mais claro).
Aqui tem um link legal demonstrando como fazer essa tipagem para eventos de `onChange` no react:
https://www.kindacode.com/article/react-typescript-handling-input-onchange-event/

2022-10-16 23:10 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
> +        {value === "" ? (
A indentação do código ta bem bagunçada, instala os plugins do Eslint e Prettier e configura o `Vscode` para formatar ao salvar.

2022-10-16 23:10 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
> +import {FileEarmarkArrowUp} from 'react-bootstrap-icons';
Essa lib não foi adicionada ao projeto e ta quebrando quando vamos tentar rodar.

2022-10-16 23:10 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
> +import {FileEarmarkArrowUp} from 'react-bootstrap-icons';
<img width="630" alt="image" src="https://user-images.githubusercontent.com/22357579/196062772-9bbcd55c-5c46-446d-abba-809a1559ca29.png">

2022-10-16 23:10 UTC, tuliocll commented on components/inputs/InputUpload/style.module.css
> +.titulo{
Vamos deixar as declarações todas em ingles, para seguir o padrão.

2022-10-16 23:10 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
> +          <input id={id} type="file" onChange={handleSubmit}  className={style["upload-input"]} {...rest}/>
O `onChange` esta sendo usado interno no componente e não tem nenhuma forma de pegarmos essa alteração no componente pai (que é onde precisamos receber esse arquivo feito upload), aqui vale a pena criar uma prop chamada de `onChange` também e invocar ela toda vez que chamamos a `handleSubmit`, passando pra frente o event ou até o arquivo (files[0]).

2022-10-20 21:54 UTC, bruno34154 commented
atualizações feitas

2022-10-25 10:33 UTC, tuliocll requested changes

2022-10-25 10:33 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
> +      onChange;
não entendi essa parte, funciona dessa forma ?
o ideal seria chamar o `onChange();` normalmente.

2022-10-25 10:33 UTC, tuliocll commented on components/inputs/InputUpload/style.module.css
> +.container-upload > label {
Da uma olhada nessa configuracao do vscode:
https://w3guides.com/tutorial/vscode-auto-format-on-save

2022-10-25 10:33 UTC, tuliocll commented on pages/index.tsx
> +      <InputUpload id="upload" placeholder="selecione um arquivo" title="Imagem"/>
Chama o `onChange` aqui tambem e cria uma função para testar se ele ta retornando mesmo

2022-10-25 10:33 UTC, tuliocll commented on components/inputs/InputUpload/index.tsx
> +  const handleSubmit = async (event) => {
Faltou a tipagem do `event`.

2022-11-05 21:46 UTC, bruno34154 commented
subi as mundanças requeridas dá uma olhada por favor

2022-11-06 00:26 UTC, tuliocll approved these changes

2022-11-06 00:26 UTC, merged